// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddressButton: typeof import('./common/components/metamask/AddressButton.vue')['default']
    AnalysisTable: typeof import('./analysis/components/analysisTable.vue')['default']
    'Carbon:close': typeof import('~icons/carbon/close')['default']
    'Carbon:cloudUpload': typeof import('~icons/carbon/cloud-upload')['default']
    'Carbon:exit': typeof import('~icons/carbon/exit')['default']
    'Carbon:ica2d': typeof import('~icons/carbon/ica2d')['default']
    'Carbon:orderDetails': typeof import('~icons/carbon/order-details')['default']
    'Carbon:settings': typeof import('~icons/carbon/settings')['default']
    CarbonDataEnrichment: typeof import('~icons/carbon/data-enrichment')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonReset: typeof import('~icons/carbon/reset')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    CircleCloseFilled: typeof import('~icons/ci/rcle-close-filled')['default']
    ConnectWalletButton: typeof import('./common/components/metamask/ConnectWalletButton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./common/components/Footer.vue')['default']
    Header: typeof import('./common/components/Header.vue')['default']
    ImportDrawer: typeof import('./analysis/components/importDrawer.vue')['default']
    JazzIcon: typeof import('./common/components/metamask/JazzIcon.vue')['default']
    Navbar: typeof import('./common/components/dashboard/Navbar.vue')['default']
    QuickView: typeof import('./analysis/components/quickView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./common/components/dashboard/Sidebar.vue')['default']
    Spinner: typeof import('./common/components/metamask/Spinner.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
