"""generate database

Revision ID: 2d276920e1cf
Revises: 
Create Date: 2023-03-24 13:21:15.745478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d276920e1cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    categories = op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    key_factors = op.create_table('key_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    prediction_errors = op.create_table('prediction_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('img_bytes', sa.LargeBinary(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('prediction', sa.String(length=255), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    tags = op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    diseases = op.create_table('diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    disease_key_factors = op.create_table('disease_key_factors',
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('key_factor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['key_factor_id'], ['key_factors.id'], )
    )
    disease_tags = op.create_table('disease_tags',
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###

    ### Added data ###
    op.bulk_insert(
        categories,
        [
            {
                'id': 1,
                'name': 'Alzheimer',
            },
            {
                'id': 2,
                'name': 'Pneumonia',
            }
        ],
    )

    op.bulk_insert(
        key_factors,
        [
            {
                'id': 1,
                'name': 'Age',
            },
            {
                'id': 2,
                'name': 'Weak immune system',
            },
            {
                'id': 3,
                'name': 'Smoking',
            },
            {
                'id': 4,
                'name': 'Obesity',
            },
            {
                'id': 5,
                'name': 'Diabetes',
            },
            {
                'id': 6,
                'name': 'Genetics',
            },
            {
                'id': 7,
                'name': 'Life style',
            },
            {
                'id': 8,
                'name': 'Head injuries'
            },
        ],
    )

    op.bulk_insert(
        tags,
        [
            {
                'id': 1,
                'name': 'Lung',
                'color': '#FF0000',
            },
            {
                'id': 2,
                'name': 'Brain',
                'color': '#00FF00',
            },
            {
                'id': 3,
                'name': 'Low mortality rate',
                'color': '#0000FF',
            },
            {
                'id': 4,
                'name': 'High mortality rate',
                'color': '#FFFF00',
            },
            {
                'id': 5,
                'name': 'Highly contagious',
                'color': '#00FFFF',
            },
            {
                'id': 6,
                'name': 'Not contagious',
                'color': '#FF00FF',
            }
        ],
    )

    op.bulk_insert(
        diseases,
        [
            {
                'id': 1,
                'name': 'Alzheimer',
                'description': 'Alzheimer\'s disease is a progressive neurodegenerative disease that usually starts slowly and gets worse over time. It is the most common cause of dementia among older adults.',
                'category_id': 1,
            },
            {
                'id': 2,
                'name': 'Pneumonia',
                'description': 'Pneumonia is an infection that inflames the air sacs in one or both lungs. The air sacs may fill with fluid or pus (purulent material), causing cough with phlegm or pus, fever, chills, and difficulty breathing. A variety of organisms, including bacteria, viruses and fungi, can cause pneumonia. The severity of the illness can range from mild to life-threatening.',
                'category_id': 2,
            }
        ],
    )

    op.bulk_insert(
        disease_key_factors,
        [
            {
                'disease_id': 1,
                'key_factor_id': 1,
            },
            {
                'disease_id': 1,
                'key_factor_id': 6,
            },
            {
                'disease_id': 1,
                'key_factor_id': 7,
            },
            {
                'disease_id': 2,
                'key_factor_id': 1,
            },
            {
                'disease_id': 2,
                'key_factor_id': 2,
            },
            {
                'disease_id': 2,
                'key_factor_id': 5,
            },
            {
                'disease_id': 2,
                'key_factor_id': 7,
            },
        ],
    )

    op.bulk_insert(
        disease_tags,
        [
            {
                'disease_id': 1,
                'tag_id': 2,
            },
            {
                'disease_id': 1,
                'tag_id': 4,
            },
            {
                'disease_id': 2,
                'tag_id': 1,
            },
            {
                'disease_id': 2,
                'tag_id': 3,
            },
            {
                'disease_id': 2,
                'tag_id': 5,
            },
        ],
    )

    ### End added data ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disease_tags')
    op.drop_table('disease_key_factors')
    op.drop_table('diseases')
    op.drop_table('tags')
    op.drop_table('prediction_errors')
    op.drop_table('key_factors')
    op.drop_table('categories')
    # ### end Alembic commands ###
